# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XESDataBaseDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XESDataBaseDemo
#    pod 'FMDB'
    pod 'FMDBMigrationManager', '~> 1.4.1'

  target 'XESDataBaseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XESDataBaseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
